version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: startup/install_dependencies
      timeout: 300
      runas: root
    - location: startup/start_server
      timeout: 300
      runas: root