version: 0.0
os: linux
files:
  - source: /home/ec2-user
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: startup/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root