version: 0.0
os: linux
files:
  - source: /static/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: startup/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: startup/start_server
      timeout: 300
      runas: root